[package]
name = "pie"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = true

[dependencies]
libc = { version = "0.2.142", default-features = false }
